"""init 

Revision ID: 133f07ac349c
Revises: 
Create Date: 2021-05-20 16:41:02.881905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133f07ac349c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_mpesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=250), nullable=True),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_added')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=250), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=48), nullable=False),
    sa.Column('phoneNumber', sa.String(length=12), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_table('help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('branch', sa.Integer(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mpesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('receipt_number', sa.String(length=250), nullable=True),
    sa.Column('transaction_date', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=250), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=250), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=250), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=False),
    sa.Column('result_desc', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('local_transactional_key', sa.String(length=250), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('start', sa.String(length=200), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('ticket', sa.String(length=6), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('next', sa.Boolean(), nullable=False),
    sa.Column('serviced', sa.Boolean(), nullable=False),
    sa.Column('teller', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=250), nullable=True),
    sa.Column('use_teller', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phrase')
    )
    op.create_table('reset_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=250), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=250), nullable=True),
    sa.Column('is_medical', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('branch', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('unique_id', sa.String(length=250), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('branch_unique_id', sa.String(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('teller_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teller_to', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('teller_from', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('pre_req', sa.Integer(), nullable=True),
    sa.Column('preq_date_servived', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=48), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('account_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('opens', sa.String(length=50), nullable=True),
    sa.Column('closes', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('key_', sa.Text(), nullable=True),
    sa.Column('valid_till', sa.DateTime(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('unique_id', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['company.name'], ),
    sa.ForeignKeyConstraint(['service'], ['service.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('image_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=250), nullable=True),
    sa.Column('start', sa.String(length=200), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=6), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('nxt', sa.Integer(), nullable=False),
    sa.Column('serviced', sa.Boolean(), nullable=False),
    sa.Column('teller', sa.String(length=250), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('is_instant', sa.Boolean(), nullable=True),
    sa.Column('forwarded', sa.Boolean(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('unique_id', sa.String(length=250), nullable=True),
    sa.Column('unique_teller', sa.String(length=250), nullable=True),
    sa.Column('verify', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_added'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('service_offered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('teller', sa.String(length=100), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('unique_id', sa.String(length=250), nullable=True),
    sa.Column('medical_active', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('booking_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('service', sa.String(length=250), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['service_offered.unique_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_times')
    op.drop_table('service_offered')
    op.drop_table('booking')
    op.drop_table('recovery')
    op.drop_table('image_company')
    op.drop_table('branch')
    op.drop_table('account_status')
    op.drop_table('video')
    op.drop_table('user')
    op.drop_table('teller_booking')
    op.drop_table('teller')
    op.drop_table('service')
    op.drop_table('reset_option')
    op.drop_table('phrase')
    op.drop_table('payments')
    op.drop_table('online_booking')
    op.drop_table('mpesa')
    op.drop_table('icon')
    op.drop_table('help')
    op.drop_table('customer')
    op.drop_table('company')
    op.drop_table('booking_mpesa')
    # ### end Alembic commands ###
