"""department_service added 

Revision ID: 7a1777433fed
Revises: 9893e0d070a6
Create Date: 2021-06-22 17:13:04.400625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1777433fed'
down_revision = '9893e0d070a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.String(length=250), nullable=False),
    sa.Column('service_id', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.unique_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_offered.unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_service')
    # ### end Alembic commands ###
