"""service _unique 

Revision ID: a0b7a37499e4
Revises: 7a1777433fed
Create Date: 2021-06-23 21:28:28.565712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b7a37499e4'
down_revision = '7a1777433fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'department_service', ['service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department_service', type_='unique')
    # ### end Alembic commands ###
